M48
; DRILL file {KiCad 8.0.4} date 2024-08-02T16:31:52-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-08-02T16:31:52-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C4.890
%
G90
G05
T1
X210.86Y-116.25
X216.64Y-116.25
T2
X201.5Y-91.25
X206.5Y-91.25
T3
X230.75Y-65.35
X230.75Y-89.65
M30
